on:
  push:
    branches:
      - 'main'
    tags:
      - 'v*'

name: Build PDFs

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Build PDFs
        uses: docker://ghcr.io/swissmanu/pandoc:latest
        with:
          args: make

      # This step runs only on the main branch:
      - uses: actions/upload-artifact@v2
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          name: paper
          path: out/paper.pdf
      - uses: actions/upload-artifact@v2
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          name: reports
          path: out/reports.pdf

      # Following Steps run only on version tags:
      - name: Extract Version from Tag
        id: get_version
        if: ${{ github.ref != 'refs/heads/main' }}
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}

      - name: ZIP Release Assets
        if: ${{ github.ref != 'refs/heads/main' }}
        run: |
          zip --junk-paths release-assets.zip ./out/paper.pdf ./out/reports.pdf

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        if: ${{ github.ref != 'refs/heads/main' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false

      - name: Upload Release Asset
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        if: ${{ github.ref != 'refs/heads/main' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: release-assets.zip
          asset_name: paper-and-report-${{ steps.get_version.outputs.VERSION }}.zip
          asset_content_type: application/zip
